### ISSUE TITLE
callback for fs.WriteStream

### ISSUE THREAD

**Issue by fleg** [juliangruber/multipipe#35] opened 2016-08-10 07:38 UTC
```js
multipipe(
	fs.createReadStream(src),
	fs.createWriteStream(dest),
	callback
);
```
In some cases `dest` file could be empty, because fs.WriteStream emit `finish` and then `close`, but after `finish` multipipe stop listening events:
```js
  if (cb) {
    var ended = false;
    ret.on('error', end);
    last.on('finish', end);
    last.on('close', end);
    function end(err){
      if (ended) return;
      ended = true;
      cb(err);
    }
  }
```
[Documentation](https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_event_close_1) says that `close`
> Emitted when the WriteStream's underlying file descriptor has been closed using the fs.close() method.

Any suggestions how to fix that?

**Comment by juliangruber** [comment] 2016-08-10 08:30
the problem is that not all streams emit `"close"`, so if we just listen for this event others might never call the callback.

i think the proper solutions here is to check if a stream is an fs stream and in that case only listen for `"close"`. i'll work on a pull request to add this.

**Comment by juliangruber** [comment] 2016-08-10 08:36
actually, i can't replicate. i used this test script to check if after the `"finish"` event the file has been written out:

```js
var fs = require('fs')

var file = '/tmp/test.txt'
fs.unlinkSync(file)
var ws = fs.createWriteStream(file)
ws.end('ok')
ws.on('finish', function () {
  console.log(fs.readFileSync(file, 'utf8'))
})
```

and i always get the "ok".

I also created a test case using multipipe and it always returns the file:

```js
var pipe = require('.')
var fs = require('fs')

var file = '/tmp/test.txt'
fs.unlinkSync(file)

pipe(
  fs.createReadStream('index.js'),
  fs.createWriteStream(file),
  function (err) {
    if (err) throw err
    console.log(fs.readFileSync(file, 'utf8'))
  }  
)
```

Can you give me a test script to reproduce this issue?

**Comment by fleg** [comment] 2016-08-10 09:28
It's really hard to reproduce, give me some time

**Comment by juliangruber** [comment] 2016-08-10 09:33
by the way you can also just do

```js
pipe(
  fs.createReadStream(src),
  fs.createWriteStream(dst).on('close', function () {
    // ...
  }),
  function (err) {
    if (err) ...
  }
)
```

**Comment by juliangruber** [comment] 2016-08-10 09:34
actually i think this is the proper solution, as usually even with fs streams the `"finish"` event is what you want, there's an extra delay until `"close"` happens. i'm closing this referring to the comment above for a solution.

**Closed by juliangruber** 2016-08-10 09:34 UTC

**Comment by fleg** [comment] 2016-08-10 09:38
Ooh, it my mistake, I found bug in my code
